#expt inserts
insert into search_experiment values(default, 'MCM3', 12089153, 'e2f', 'Arabidopsis', 'Northern blot', '1 experiment', 'Wild-type vs binding site mutant', 'High quality');
insert into search_experiment values(default, 'MCM3', 12089153, 'e2f', 'Arabidopsis', 'EMSA', '1 experiment', 'Wild-type vs mutant competitors', 'Medium quality');
insert into search_experiment values(default, 'MCM3', 12089153, 'e2f', 'Arabidopsis', 'Reporter gene assay', '3 replicates', 'Wild-type vs over-expression of E2fa/binding site mutant', '-1.5 fold');
insert into search_experiment values(default, 'MCM3', 12089153, 'e2f', 'Arabidopsis', 'Reporter gene assay', '50 replicates', 'Wild-type vs binding site mutant ', null);
insert into search_experiment values(default, null, 18555785, 'e2f', 'Mouse', 'ChIP-seq', 'GSE11431', null, null);
insert into search_experiment values(default, null, 18555785, 'e2f', 'Mouse', 'ChIP-qPCR', 'Table S4 ', null, null);
insert into search_experiment values(default, 'Apaf1', 12982983, 'e2f', 'Human', 'ChIP', '1 experiment', 'Wild-type vs mutant', 'Good quality');
insert into search_experiment values(default, 'Asf1b', 19084398, 'e2f', 'Human', 'ChIP', '1 experiment', 'Wild-type vs over-expression  ', 'Poor quality');
insert into search_experiment values(default, 'Atad2', 18973773, 'e2f', 'Human', 'IHC', '1 experiment', 'Wild-type vs mutant', 'Good quality');
insert into search_experiment values(default, 'Atm', 19073489, 'e2f', 'Human', 'qPCR', '3 replicates', 'Wild-type vs over-expression  ', '2 fold');
insert into search_experiment values(default, 'Bnip3', 18783473, 'e2f', 'Mouse', 'Western blot', '1 experiment', 'Wild-type vs mutant', 'Good quality');
insert into search_experiment values(default, 'Bok', 16624723, 'e2f', 'Human', 'ChIP', '1 experiment', 'Wild-type vs mutant', 'Poor quality');
insert into search_experiment values(default, 'Brca1', 12329080, 'e2f', 'Mouse', 'qPCR', '3 replicates', 'Wild-type vs mutant', '-4 fold');
insert into search_experiment values(default, 'Brca2', 19039021, 'e2f', 'Mouse', 'Reporter gene assay', '3 replicates', 'Wild-type vs over-expression  ', '2 fold');
insert into search_experiment values(default, 'Brd2', 17863478, 'e2f', 'Human', 'Northern blot', '1 experiment', 'Wild-type vs over-expression  ', 'Good quality');
insert into search_experiment values(default, 'Brip1', 12367823, 'e2f', 'Human', 'ChIP-qPCR', '3 replicates', 'Wild-type vs mutant', '10 fold');
insert into search_experiment values(default, 'Bub3', 19078432, 'e2f', 'Human', 'Western blot', '1 experiment', 'Wild-type vs mutant', 'Poor quality');
insert into search_experiment values(default, 'Cav1', 17862348, 'e2f', 'Mouse', 'ChIP', '1 experiment', 'Wild-type vs over-expression  ', 'Good quality');
insert into search_experiment values(default, 'Cbx5', 17864123, 'e2f', 'Rat', 'Reporter gene assay', null, 'Wild-type vs over-expression  ', '3 fold');
insert into search_experiment values(default, 'Ccna1', 14322390, 'e2f', 'Mouse', 'EMSA', '1 experiment', 'Wild-type vs mutant', 'Good quality');
insert into search_experiment values(default, 'Ccna2', 17857823, 'e2f', 'Human', 'EMSA', '1 experiment', 'Wild-type vs mutant', 'Good quality');
insert into search_experiment values(default, 'Ccnb1', 18972350, 'e2f', 'Human', 'ChIP', '1 experiment', 'Wild-type vs mutant', 'Medium quality');
insert into search_experiment values(default, null, 12695333, 'myc', 'HUMAN', 'ChIP', 'Supplemental Table A', null, null);
insert into search_experiment values(default, null, 12808131, 'myc', 'HUMAN', 'Microarray', 'Supporting Raw Data Set', null, null);
insert into search_experiment values(default, 'ATF4', 12808131, 'myc', 'HUMAN', 'ChIP', null, null, 'medium');
insert into search_experiment values(default, 'MARS', 12808131, 'myc', 'HUMAN', 'ChIP', null, null, 'high');

#transcription table inserts
insert into search_transcription values(default, 1,  'null');
insert into search_transcription values(default, 2,  'E2Fc');
insert into search_transcription values(default, 2,  'E2Fd');
insert into search_transcription values(default, 3,  'E2Fa');
insert into search_transcription values(default, 4,  'null');
insert into search_transcription values(default, 5,  'E2f1');
insert into search_transcription values(default, 6,  'E2f1');
insert into search_transcription values(default, 7,  'E2F3');
insert into search_transcription values(default, 8,  'E2F5');
insert into search_transcription values(default, 9,  'E2F8');
insert into search_transcription values(default, 10,  'E2F8');
insert into search_transcription values(default, 11,  'E2F1');
insert into search_transcription values(default, 12,  'E2F1');
insert into search_transcription values(default, 13,  'E2F3b');
insert into search_transcription values(default, 14,  'E2F1');
insert into search_transcription values(default, 15,  'E2F1');
insert into search_transcription values(default, 16,  'E2F3a');
insert into search_transcription values(default, 17,  'E2F7');
insert into search_transcription values(default, 18,  'E2F1');
insert into search_transcription values(default, 19,  'E2F2');
insert into search_transcription values(default, 20,  'E2F7');
insert into search_transcription values(default, 21,  'E2F2');
insert into search_transcription values(default, 22,  'E2F1');
insert into search_transcription values(default, 23,  'C');
insert into search_transcription values(default, 24,  'C');
insert into search_transcription values(default, 25,  'C');
insert into search_transcription values(default, 26,  'C');

#tissue inserts
insert into search_tissue values(default, 1,  'BY2 cell line');
insert into search_tissue values(default, 2,  'BY2 cell line');
insert into search_tissue values(default, 3,  'BY2 cell line');
insert into search_tissue values(default, 4,  'Meristem');
insert into search_tissue values(default, 5,  'Mouse Embryonic stem cells');
insert into search_tissue values(default, 6,  'Mouse Embryonic stem cells');
insert into search_tissue values(default, 7,  'Liver');
insert into search_tissue values(default, 8,  'PBR cell line');
insert into search_tissue values(default, 9,  'K cell line');
insert into search_tissue values(default, 10,  'Liver');
insert into search_tissue values(default, 11,  'Bladder');
insert into search_tissue values(default, 12,  'Endothelial cell line');
insert into search_tissue values(default, 13,  'Lung');
insert into search_tissue values(default, 14,  'Breast');
insert into search_tissue values(default, 15,  'Hela cell line');
insert into search_tissue values(default, 16,  'Breast');
insert into search_tissue values(default, 17,  'Brain');
insert into search_tissue values(default, 18,  'Lung');
insert into search_tissue values(default, 19,  'H cell line');
insert into search_tissue values(default, 20,  'Bone-marrow');
insert into search_tissue values(default, 21,  'Hela cell line');
insert into search_tissue values(default, 22,  'BT cell line');
insert into search_tissue values(default, 23,  'Cell Line U-937');
insert into search_tissue values(default, 23,  'Cell Line HL60');
insert into search_tissue values(default, 23,  'Cell Line P493');
insert into search_tissue values(default, 23,  'Cell Line T98G');
insert into search_tissue values(default, 23,  'Cell Line WS1');
insert into search_tissue values(default, 24,  'Daudi Cell Line');
insert into search_tissue values(default, 25,  'Daudi Cell Line');
insert into search_tissue values(default, 26,  'Daudi Cell Line');

